import { McpServer, ResourceTemplate } from "@modelcontextprotocol/server";
import { z } from "zod";
import { ServiceError } from "../core/errors.js";
import { CustodyPathStatusSchema, ParticipantProfileSchema, StacksNetworkSchema, toJsonSafe } from "../core/schemas.js";
import { CAPABILITIES, GLOSSARY, YIELD_METHODOLOGY } from "../content.js";
import { BitcoinStakingService } from "../service.js";
import { SecurityTopicValues } from "../security.js";
import { INSTITUTIONAL_RESPONSE_STANDARD, SOURCE_METHODOLOGY } from "../institutional.js";
import {
  BondOutputSchema, BondsOutputSchema, ComparisonOutputSchema, CompatibilityOutputSchema,
  CustodyOutputSchema, DiligenceOutputSchema, MarketSnapshotOutputSchema, ParticipantOutputSchema,
  PlanOutputSchema, ProtocolBondsOutputSchema, ProtocolStatusOutputSchema, RoutesOutputSchema,
  SecurityOutputSchema, YieldOutputSchema,
} from "./output-schemas.js";

export const SERVER_VERSION = "0.3.0";
export const CONTRACT_VERSION = "2.0.0";
export const SKILL_VERSION = "0.3.1";
export const EXPECTED_TOOL_NAMES = [
  "get_market_snapshot", "get_protocol_status", "list_protocol_bonds", "get_security_guidance", "build_diligence_report",
  "list_bonds", "list_custody_paths", "list_bond_participation_routes", "get_bond", "check_participant_status",
  "check_compatibility", "simulate_yield", "compare_staking_paths", "build_participation_plan",
] as const;

const readOnlyAnnotations = { readOnlyHint: true, destructiveHint: false, openWorldHint: false } as const;
const liveReadAnnotations = { ...readOnlyAnnotations, openWorldHint: true } as const;
export const SERVER_INSTRUCTIONS = [
  "This server is a read-only Bitcoin Staking intelligence layer. Use its tools and resources for structured facts, calculations, source provenance, and verification boundaries.",
  "Treat current runtime and on-chain evidence as stronger than product-owner claims, and apply returned freshness and conflict status before describing anything as current or available.",
  "Do not replace unavailable live data with demo, stale, remembered, or inferred state. Preserve unknown and empty results as unknown and empty.",
  "Use simulate_yield only when duration and annual rate are sourced or explicitly supplied. Never assume a missing route or LST fee is zero.",
  "Never construct, sign, or broadcast transactions, move funds, or provide individualized financial advice.",
].join(" ");

const CONCIERGE_INSTRUCTIONS = [
  "Classify the newest request before responding. Onboarding follows the user's intent, not simply whether this is the first message.",
  "For an empty invocation or broad orientation such as 'I'd like to get started with Bitcoin staking' that has no concrete question, amount, provider, or preference, give a capability-first welcome of fewer than 100 words.",
  "The concierge's user-facing name is Scout. Scout is a warm, professional guide: approachable without being cute, confident without implying certainty, and helpful without pretending to be human or a financial adviser. Introduce the name in general onboarding, but do not repeat the introduction in every answer.",
  "Start with exactly: 'Hi, I'm Scout, your Bitcoin Staking Concierge. I can guide you through the process and answer your questions about earning rewards from BTC through the Stacks protocol.'",
  "Then say 'Here's what I can help you with:' and list only these four capabilities: Find current and upcoming opportunities; Compare ways to participate; Understand rewards, lockups, fees, and risks; Build a personalized step-by-step participation plan.",
  "Then say 'Try asking:' and offer exactly these three prompts: 'When is the next bond launching?'; 'How can I get started staking?'; 'Which participation option is right for me?'",
  "Do not lead this general welcome with an upcoming bond, route details, dates, protocol status, a network question, a tool menu, or a routing question.",
  "If the request asks a specific question, skip the general welcome and answer that intent directly. For opportunity or timing, call get_market_snapshot and lead with what is open or coming next. A direct how-to-participate question, including 'How can I get started staking?', is participation intent: compare the relevant routes and ask only the next route-changing question. For rewards, lockups, fees, risks, custody, or liquidity, answer only that topic with relevant MCP evidence. If the request includes an amount, wallet, custodian, or preference, proceed directly to the comparison or participation-plan workflow.",
  "For a general how-to-participate request with no supplied preference, frame the first choice around retaining control of native BTC on Bitcoin L1 through a preferred wallet or custody provider versus potentially using a staked BTC position in DeFi. Describe the direct route as retaining control of native BTC through the user's preferred supported wallet or custody provider. Do not equate this route with using only a self-custody wallet. Describe it without adding 'No conversion to sBTC is required.' Resolve current software, hardware, multisig, institutional-wallet, and custody options from list_custody_paths rather than a fixed provider list. Describe the pooled route first as 'Join a pool' rather than as a smaller-balance route or a specific operator. Ask: 'Which matters more to you: retaining control of native BTC on Bitcoin L1 through your preferred wallet or custody provider, or potentially using your staked BTC position in DeFi for borrowing, lending, and additional yield opportunities?'",
  "Treat the newest user request as the controlling scope. Do not carry a wallet, custodian, borrowing goal, amount, or named entity forward from an earlier turn unless the current request explicitly reconnects it.",
  "Treat allocation and enrollment mechanics as silent background context, not an investor-facing checklist. Do not proactively mention address binding, allocation immutability, partial enrollment or top-ups, overlapping-address rules, UTXO mechanics, rollover windows, reserve operations, or split-wallet handoffs. Discuss one of these only when the user asks about it, it materially changes the selected route or immediate next step, or it is needed to correct a false assumption in the user's stated plan. Use current MCP evidence for the factual answer; this background context tells you when to check, not what to claim without evidence.",
  "Do not say that a user is fully enrolled based only on a Bitcoin funding or lock transaction. When enrollment completion is the topic, confirm from current MCP evidence whether the required Stacks registration is complete; if the MCP cannot verify it, say so. Mention provider-specific setup requirements only when the user names that provider or presents a concrete custody plan for it.",
  "Before route selection, ask only a route-changing question. After route selection or a concrete plan request, ask only the single next operational question needed to proceed; do not launch a readiness questionnaire.",
  "For 'Has the protocol been audited?', state the published audit claim and name the reviewers without volunteering report-availability, scope, findings, remediation, or commit-attestation gaps. Only if the user asks for the audit documents or those details, check current MCP evidence: provide any returned public report links, or, if none are returned, say that the current evidence does not include them and direct the user to the Bitcoin Staking team for access. Do not mention BitGo or another named integration unless the current request asks whether it was covered.",
  "For a broad question such as 'How will I know my Bitcoin is safe?', call get_security_guidance with all and use a security-foundation, independent-verification, bounded-residual-risk sequence. Lead with 'Security starts with Bitcoin itself.' For the direct native-L1 route, explain from current evidence that BTC remains on Bitcoin in a P2WSH output whose script commits to the chosen wallet or custody key and the unlock conditions, and that after maturity the committed key can authorize recovery of the BTC without relying on the early-exit signer set. Then explain the applicable audit evidence and concrete checks: independently derive the expected Bitcoin address; verify the destination, amount, network, and committed key before signing; retain recovery information; and rehearse the complete lock-and-recovery flow with the intended wallet or custody path. Then say plainly: 'Like any financial software, risk is not zero,' and name only supported implementation and operational risks. Do not open with 'your Bitcoin cannot be guaranteed completely safe', a blanket disclaimer, or an unsupported superlative. Earn confidence with the sourced mechanism and verification controls before acknowledging residual risk. Never apply native-L1 Bitcoin-script protections to a pool-based route; identify the route boundary when it changes the answer.",
  "Explain two stable route types when route detail is relevant: direct native-L1 participation and pool-based participation. There may be multiple pools with different input assets, operators, and LST designs. Get current pool names, requirements, token designs, terms, and integrations from MCP evidence rather than these instructions.",
  "Apply runtime-over-owner conflict precedence and freshness before calling anything current. Write in direct, natural language and lead with the user-facing answer rather than protocol state or evidence mechanics.",
  "Keep diligence in the reasoning. Mention only caveats and unknowns that change the answer, the decision, or the next step. Translate internal status fields into ordinary sentences. For timing, name the bond and use the current launch date returned by MCP evidence; never retain a current date in these instructions. Mention on-chain configuration only when the user asks about readiness or when it changes participation.",
  "State a supported capability first and explain how it works. Do not manufacture a negative contrast around it with phrases such as 'but it is', 'rather than', 'not instant', 'however', or 'the downside is'. If a material limitation changes the decision, state it plainly in its own sentence after the mechanism. Explain user actions and outcomes before infrastructure terminology. For early exit, state that PoX-5 supports an optional early-exit path, then check current bond and route evidence before saying the user can use it. When a bond enables it, explain the Stacks transaction and later Bitcoin wallet approval in user order, then state the reward, paired-STX, and network-fee effects directly. Use terms such as 'Early Exit Coordinator', 'co-signed reclaim transaction', '2-of-2', 'unlock material', and 'signer set' only when the user asks for technical detail.",
  "In a general opportunity answer, describe a pool-specific LST naturally only when current MCP evidence returns it; explain the route taxonomy only when it matters. Do not list unverified liquidity, redemption, borrowing, market, or DeFi details unless the user asks about them or they change the recommendation.",
  "For a wallet- or custody-only question, answer with the current supported options. Do not append a generic caveat that wallet support does not establish bond enrollment or availability; mention enrollment only when the user asks about it or it changes which wallet can be used.",
  "When an amount is accepted by the route assessment, proceed to the remaining eligibility, wallet, and operational decisions. Do not narrate the absence of an amount-related rejection.",
  "For a general yield question without an amount, read the current bond economics and lead with supported planned terms rather than with missing final terms. State the returned annualized rate, approximate term, and reward asset. Call simulate_yield with a 1 BTC principal for the deterministic gross-return example before applicable fees; do not calculate the worked return in prose. Invite the user to provide their BTC amount for a personalized estimate. Keep planned product targets and public reference-model assumptions distinct from bond-specific terms and final on-chain configured terms. Never retain a current rate, duration, reward asset, fee, capacity, or worked return in these instructions.",
  "For a yield question, call simulate_yield when duration and annual rate are sourced or explicitly supplied. If an applicable route or selected-LST fee is missing, show the sourced gross reward, label net reward unknown, and never assume a zero fee. CoinGecko prices may enrich the scenario, but do not replace missing rate or duration inputs. Use only three-decimal display fields for user-facing BTC and STX quantities.",
  "Use the positive planned-yield structure above with values returned by current MCP evidence and deterministic calculations. State only the economics returned by the MCP or explicitly supplied by the user. Avoid stacked qualifiers and status jargon such as scheduled-not-open, optional capability, is intended to provide, or exhaustive lists ending in not yet verified.",
  "For borrowing, require a named live lender and sourced collateral terms; transferability alone is never borrowing evidence. Accept BTC or sBTC amounts naturally and convert to sats internally. Never expose internal enums or basis points unless requested. Never construct, sign, or broadcast transactions or provide individualized advice.",
].join(" ");

function conciergePromptText(request?: string) {
  return `${request ? `Current user request: ${request}` : "This is an empty first-run invocation."}\n\n${CONCIERGE_INSTRUCTIONS}`;
}

function success(value: unknown) { const structuredContent = toJsonSafe(value) as Record<string, unknown>; return { structuredContent, content: [{ type: "text" as const, text: JSON.stringify(structuredContent, null, 2) }] }; }
function failure(error: unknown) { const serviceError = error instanceof ServiceError ? error : new ServiceError("INVALID_INPUT", error instanceof Error ? error.message : "Unknown request failure."); return { isError: true, content: [{ type: "text" as const, text: JSON.stringify({ error: { code: serviceError.code, message: serviceError.message, retryable: serviceError.retryable } }, null, 2) }] }; }
function tool<T>(handler: () => Promise<T> | T) { return Promise.resolve().then(handler).then(success).catch(failure); }

export function createBitcoinStakingMcpServer(service = new BitcoinStakingService()): McpServer {
  const server = new McpServer({ name: "bitcoin-staking-mcp", version: SERVER_VERSION }, { instructions: SERVER_INSTRUCTIONS });

  server.registerTool("get_market_snapshot", { title: "Get Bitcoin Staking market snapshot", description: "Deterministic front door combining the reviewed product registry, route freshness, live PoX state, and on-chain bond configuration with evidence precedence already applied.", inputSchema: z.object({ network: StacksNetworkSchema.default("mainnet") }), outputSchema: MarketSnapshotOutputSchema, annotations: liveReadAnnotations }, ({ network }) => tool(() => service.getMarketSnapshot({ network })));
  server.registerTool("get_protocol_status", { title: "Get Bitcoin Staking protocol status", description: "Read current PoX state and exact endpoint provenance.", inputSchema: z.object({ network: StacksNetworkSchema.default("mainnet") }), outputSchema: ProtocolStatusOutputSchema, annotations: liveReadAnnotations }, ({ network }) => tool(() => service.getProtocolStatus(network)));
  server.registerTool("list_protocol_bonds", { title: "List live PoX-5 protocol bonds", description: "Scan a bounded PoX-5 window and return only on-chain configured bonds.", inputSchema: z.object({ network: StacksNetworkSchema.default("mainnet"), lookbackPeriods: z.number().int().min(0).max(24).default(6), lookaheadPeriods: z.number().int().min(0).max(12).default(2) }), outputSchema: ProtocolBondsOutputSchema, annotations: liveReadAnnotations }, ({ network, lookbackPeriods, lookaheadPeriods }) => tool(() => service.listProtocolBonds(network, { lookbackPeriods, lookaheadPeriods })));
  server.registerTool("get_security_guidance", { title: "Get Bitcoin Staking security guidance", description: "Return sourced security diligence with explicit evidence boundaries.", inputSchema: z.object({ topic: z.enum([...SecurityTopicValues, "all"]).default("all") }), outputSchema: SecurityOutputSchema, annotations: readOnlyAnnotations }, ({ topic }) => tool(() => service.getSecurityGuidance(topic)));
  server.registerTool("build_diligence_report", { title: "Build a bond and route diligence report", description: "Build a claim-sourced report across bond availability, protocol economics, direct and pool dependencies, optional LST risks, fit, missing evidence, and a concrete next action.", inputSchema: z.object({ network: StacksNetworkSchema.optional(), bondIndex: z.number().int().nonnegative().optional(), bondId: z.string().min(1).optional(), routeId: z.string().min(1).optional(), profile: ParticipantProfileSchema }), outputSchema: DiligenceOutputSchema, annotations: liveReadAnnotations }, (input) => tool(() => service.buildDiligenceReport(input)));
  server.registerTool("list_bonds", { title: "List Bitcoin Staking bonds", description: "List reviewed public bonds with route summaries; demo records remain excluded by default.", inputSchema: z.object({ lifecycleStatus: z.enum(["upcoming", "open", "closed", "unknown"]).optional(), includeDemo: z.boolean().default(false) }), outputSchema: BondsOutputSchema, annotations: liveReadAnnotations }, (input) => tool(() => service.listBonds(input)));
  server.registerTool("list_custody_paths", { title: "List native-L1 custody paths", description: "List current product-level custody evidence for direct native-L1 participation only.", inputSchema: z.object({ provider: z.string().min(1).optional(), status: CustodyPathStatusSchema.optional() }), outputSchema: CustodyOutputSchema, annotations: liveReadAnnotations }, (input) => tool(() => service.listCustodyPaths(input)));
  server.registerTool("list_bond_participation_routes", { title: "List a bond's participation routes", description: "Return the direct native-L1 and approved pool routes under one bond, including any registry-published LST capability offered through a pool.", inputSchema: z.object({ bondId: z.string().min(1) }), outputSchema: RoutesOutputSchema, annotations: liveReadAnnotations }, (input) => tool(() => service.listBondParticipationRoutes(input)));
  server.registerTool("get_bond", { title: "Get a Bitcoin Staking bond", description: "Get a normalized v2 bond and reconcile owner claims with on-chain state.", inputSchema: z.object({ bondId: z.string().min(1) }), outputSchema: BondOutputSchema, annotations: liveReadAnnotations }, ({ bondId }) => tool(() => service.getBond(bondId)));
  server.registerTool("check_participant_status", { title: "Check public participant status", description: "Read public participant state, infer network from the address when appropriate, reject conflicts, and return component provenance.", inputSchema: z.object({ address: z.string().min(1), bondId: z.string().min(1).optional(), network: StacksNetworkSchema.optional() }), outputSchema: ParticipantOutputSchema, annotations: liveReadAnnotations }, ({ address, bondId, network }) => tool(() => service.checkParticipantStatus(address, bondId, network)));
  server.registerTool("check_compatibility", { title: "Check direct-route custody compatibility", description: "Check one current custody path against the selected bond's direct native-L1 route.", inputSchema: z.object({ bondId: z.string().min(1), provider: z.string().min(1), keyControlPreference: z.enum(["self_controlled", "custodian", "either", "unknown"]).default("unknown") }), outputSchema: CompatibilityOutputSchema, annotations: liveReadAnnotations }, (input) => tool(() => service.checkCompatibility(input)));
  server.registerTool("simulate_yield", { title: "Simulate route-aware Bitcoin Staking yield", description: "Calculate deterministic route-aware economics only when duration, rate, and all applicable route or LST fees are complete; optional CoinGecko prices enrich the result.", inputSchema: z.object({ bondId: z.string().min(1), routeId: z.string().min(1).optional(), principalSats: z.string().regex(/^\d+$/).optional(), principalBtc: z.string().regex(/^\d+(?:\.\d{1,8})?\s*(?:s?btc)?$/i).optional(), durationDays: z.number().int().safe().positive().optional(), annualRateBps: z.number().int().safe().min(0).max(100_000).optional(), feeBps: z.number().int().safe().min(0).max(10_000).optional(), lstFeeBps: z.number().int().safe().min(0).max(10_000).optional(), includeLst: z.boolean().default(false), btcPriceUsd: z.number().positive().optional(), stxPriceScenariosUsd: z.array(z.number().positive()).max(12).optional() }).refine((value) => Boolean(value.principalSats || value.principalBtc), { message: "Provide principalSats or principalBtc." }), outputSchema: YieldOutputSchema, annotations: liveReadAnnotations }, (input) => tool(() => service.simulateYield(input)));
  server.registerTool("compare_staking_paths", { title: "Compare the two bond routes", description: "Preserved compatibility tool that compares the direct route and approved pool under the canonical published bond.", inputSchema: ParticipantProfileSchema, outputSchema: ComparisonOutputSchema, annotations: liveReadAnnotations }, (profile) => tool(() => service.compareStakingPaths(profile)));
  server.registerTool("build_participation_plan", { title: "Build a read-only participation plan", description: "Select or compare bond routes and return fit, dependencies, missing evidence, and diligence actions without transaction fields.", inputSchema: z.object({ bondId: z.string().min(1), routeId: z.string().min(1).optional(), profile: ParticipantProfileSchema }), outputSchema: PlanOutputSchema, annotations: liveReadAnnotations }, ({ bondId, routeId, profile }) => tool(() => service.buildParticipationPlan(bondId, profile, routeId)));

  server.registerResource("bitcoin-staking-capabilities", "bitcoin-staking://capabilities", { title: "Bitcoin Staking Concierge capabilities", mimeType: "text/markdown" }, async (uri) => {
    const { metadata: registry } = await service.manifests.listWithMetadata();
    const capabilities = `${CAPABILITIES}\n\nContract version: ${CONTRACT_VERSION}\nServer version: ${SERVER_VERSION}\nSkill version: ${SKILL_VERSION}\nRegistry version: ${registry.registryVersion}\nRegistry hash: ${registry.contentHash}\nRegistry review status: ${registry.reviewStatus}\nRegistry source mode: ${registry.sourceMode}\n`;
    return { contents: [{ uri: uri.href, mimeType: "text/markdown", text: capabilities }] };
  });
  server.registerResource("bitcoin-staking-glossary", "bitcoin-staking://glossary", { title: "Bitcoin Staking glossary", mimeType: "text/markdown" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "text/markdown", text: GLOSSARY }] }));
  server.registerResource("bitcoin-staking-yield-methodology", "bitcoin-staking://methodology/yield", { title: "Yield methodology", mimeType: "text/markdown" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "text/markdown", text: YIELD_METHODOLOGY }] }));
  server.registerResource("bitcoin-staking-security", "bitcoin-staking://security", { title: "Security guidance", mimeType: "application/json" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(service.getSecurityGuidance("all"), null, 2) }] }));
  server.registerResource("bitcoin-staking-custody-paths", "bitcoin-staking://custody-paths", { title: "Native-L1 custody registry", mimeType: "application/json" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(await service.listCustodyPaths(), null, 2) }] }));
  server.registerResource("bitcoin-staking-source-methodology", "bitcoin-staking://methodology/sources", { title: "Source methodology", mimeType: "text/markdown" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "text/markdown", text: SOURCE_METHODOLOGY }] }));
  server.registerResource("bitcoin-staking-institutional-response-standard", "bitcoin-staking://methodology/response-standard", { title: "Diligence response standard", mimeType: "text/markdown" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "text/markdown", text: INSTITUTIONAL_RESPONSE_STANDARD }] }));
  server.registerResource("bitcoin-staking-bond", new ResourceTemplate("bitcoin-staking://bonds/{bondId}", { list: async () => ({ resources: (await service.manifests.list()).map((bond) => ({ uri: `bitcoin-staking://bonds/${bond.id}`, name: bond.title, title: bond.dataStatus === "demo" ? `[DEMO] ${bond.title}` : bond.title, mimeType: "application/json", description: bond.description })) }), complete: { bondId: async (value) => (await service.manifests.list()).map((bond) => bond.id).filter((id) => id.startsWith(value)) } }), { title: "Bitcoin Staking bond manifest", mimeType: "application/json" }, async (uri, variables) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(toJsonSafe(await service.getBond(String(variables.bondId))), null, 2) }] }));
  server.registerResource("bitcoin-staking-source", new ResourceTemplate("bitcoin-staking://sources/{sourceId}", { list: async () => ({ resources: (await service.listSources()).map((source) => ({ uri: `bitcoin-staking://sources/${source.id}`, name: source.title, title: source.title, mimeType: "application/json", description: `${source.dataStatus} ${source.sourceType} source` })) }), complete: { sourceId: async (value) => (await service.listSources()).map((source) => source.id).filter((id) => id.startsWith(value)) } }), { title: "Bitcoin Staking source", mimeType: "application/json" }, async (uri, variables) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(await service.getSource(String(variables.sourceId)), null, 2) }] }));

  server.registerPrompt("bitcoin-staking-concierge", { title: "Scout — the Bitcoin Staking Concierge", description: "Route a user through intent-aware Bitcoin Staking onboarding and diligence.", argsSchema: z.object({ request: z.string().optional() }) }, ({ request }) => ({ messages: [{ role: "user" as const, content: { type: "text" as const, text: conciergePromptText(request) } }] }));
  return server;
}
